spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/app
    username: app
    password: app
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
    serialization:
      FAIL_ON_EMPTY_BEANS: false

app:
  version: @app.version@
  environment: app-dev

keycloak:
  realm: APP
  resource: app
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  public-client: true
  confidential-port: 0
  securityConstraints:
    - authRoles:
        - VIEW
      securityCollections:
        - name: view
          methods:
            - GET
          patterns:
            - /api/*
    - authRoles:
        - EDIT
      securityCollections:
        - name: edit
          methods:
            - GET
            - POST
          patterns:
            - /api/*