spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: ${TIME_ZONE}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: ${TIME_ZONE}
    serialization:
      FAIL_ON_EMPTY_BEANS: false

app:
  version: ${APP_VERSION}
  environment: ${APP_ENV}

keycloak:
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  auth-server-url: ${KEYCLOAK_AUTH}
  ssl-required: external
  public-client: true
  confidential-port: 0
  securityConstraints:
    - authRoles:
        - VIEW
      securityCollections:
        - name: view
          methods:
            - GET
          patterns:
            - /api/*
    - authRoles:
        - EDIT
      securityCollections:
        - name: edit
          methods:
            - GET
            - POST
          patterns:
            - /api/*